### ISSUE TITLE
Delete Old Accounts, Pre-open-source?

### ISSUE THREAD

**Issue by grgcombs** [clipperz/password-manager#123]
Any way to request a purge/delete/shred of an old Clipperz.com account?  Don't need it and don't want it lurking in the cloud.

**Comment by gcsolaroli** [comment]
Deleting an account is only possible through the interface, as we do not have the option to identify the account data on the server.
We have some issues though, that sometime prevent the completion of the delete operation due to some DB constraints preventing the transaction to be successfully committed. 😭
