### ISSUE TITLE
error logging in

### ISSUE THREAD

**Issue by cohomike** [clipperz/password-manager#165]
epsilon:

good credentials.
"error"
consistently.

**Comment by gcsolaroli** [comment]
@cohomike which version are you using?
If you are trying the new `/epsilon` (purple) with your old credentials, it will not work; please read this:
- https://clipperz.is/versions/epsilon/upgrade_to_epsilon/

[Edit] ~~If the problem is on the live (orange) version, please get in touch via email (feedback, clipperz.is).~~
Sorry, I just spotted the reference to the `/epsilon` in the original message.

**Comment by gcsolaroli** [comment]
I have just added an extra link in the `/epsilon` warning header; this should make more clear that data from previous versions are not automatically available in the new version. 🤞

**Comment by cohomike** [comment]
So before I import, I would guess I must create new credentials in e
version? Using "sign up".

mike parks

**Comment by gcsolaroli** [comment]
Correct; the new version doesn’t share anything with the current one.
