### ISSUE TITLE
MySQL extension is deprecated in PHP

### ISSUE THREAD

**Issue by jean-io** [clipperz/password-manager#88]
Hi,

I am new to Clipperz and at installation I noticed that this application use the MySQL php extension which has been deprecated: http://php.net/manual/en/function.mysql-connect.php

Thank :)

**Comment by mbarulli** [comment]
Hi Jean,
we are not able provide support for test backends. 

However, we would be glad to have a maintainer for the PHP version.  
If you are interested just get in touch!

Cheers,
Marco

**Comment by DeanCording** [comment]
The PHP backend no longer works with PHP-7.0 due to the MySQL extension being removed.

**Comment by msberends** [comment]
The support for the MySQL functions that are used here, were:

- Deprecated since March 20, 2012
- Removed on August 3, 2017

Really shocking to learn that this web app doesn't support PHP7 yet. I forked the project yesterday and replaced the MySQL functions myself: https://github.com/msberends/password-manager. You could clone that one instead of this parent project.

I also started to replace the unsafe `eval` functions as described in #55.

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.

**Comment by jean-io** [comment]
Hi 👋 Is it fixed ?

**Comment by gcsolaroli** [comment]
No, @jean-io ; the PHP backend is not supported (and no longer needed for /epsilon), so we have cleaned up some of the issues related to it that we’re still open.
